### ISSUE TITLE
Decimal precision not applying to Dart Sass

### ISSUE THREAD

**Issue by Ariane-B** [bdkjones/CodeKit#608]
**Quick, short summary:**
The option in Project settings > Languages > Sass > Sass Options > Decimal Precision doesn't work in Dart Sass.

**Expected results:**
With a precision of 4, the following:
```scss
.my-selector {
  letter-spacing: ( 1em / 14 );
}
```
Should compile to:
```css
.my-selector {
  letter-spacing: .0714em;
}
```

**Actual results:**
In Dart Sass, however, it compiles to:
```css
.my-selector {
  letter-spacing: .0714285714em;
}
```
