### ISSUE TITLE
Not applying custom target browsers config to Autoprefixer

### ISSUE THREAD

**Issue by alex-santiago** [bdkjones/CodeKit#614]
**Quick, short summary:**
It seems that Autoprefixer is not applying the custom target browser config. 
I ran the same file on Autoprefixer CSS online using the same target Browsers, and it added the prefixes for flex and transform.

**Expected results:**
```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v7.0.29,
* Autoprefixer: v9.7.6
* Browsers: >0.2%,last 2 versions,Firefox ESR,not dead,ie 9-11
*/


.some-class {
    display: -ms-flexbox;
    display: flex;
    -webkit-transform: rotate(30deg);
        -ms-transform: rotate(30deg);
            transform: rotate(30deg);
}

::-webkit-input-placeholder {
    color: gray;
}

::-moz-placeholder {
    color: gray;
}

:-ms-input-placeholder {
    color: gray;
}

::-ms-input-placeholder {
    color: gray;
}

::placeholder {
    color: gray;
}

.image {
    background-image: url(image@1x.png);
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
    .image {
        background-image: url(image@2x.png);
    }
}
```

**Actual results:**
```css
.some-class {
  display: flex;
  transform: rotate(30deg); }

::-webkit-input-placeholder {
  color: gray; }

::-moz-placeholder {
  color: gray; }

:-ms-input-placeholder {
  color: gray; }

::-ms-input-placeholder {
  color: gray; }

::placeholder {
  color: gray; }

.image {
  background-image: url(image@1x.png); }

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  .image {
    background-image: url(image@2x.png); } }
/*# sourceMappingURL=prefixes.css.map */
```

**Exact steps to reproduce:**

Using the demo on Autoprefixer's repo with an additional class that should be prefixed for ie 9.
I changed the default string for target browsers to add support for IE 9 to IE 11.
**Target Browsers:** >0.2%,last 2 versions,Firefox ESR,not dead,ie 9-11

Run the tests on https://autoprefixer.github.io/

```css
.some-class {
    display: flex;
    transform: rotate(30deg);
}

::placeholder {
    color: gray;
}

.image {
    background-image: url(image@1x.png);
}

@media (min-resolution: 2dppx) {
    .image {
        background-image: url(image@2x.png);
    }
}
```

**Your configuration (any details about your system that you think might be relevant)**
MacOS Catalina v10.15.4
CodeKit v3.12.1 build 32147
Autoprefixer 9.7.6
