### ISSUE TITLE
Using index stylesheets in scss with the new @use and @forward rules is broken

### ISSUE THREAD

**Issue by bdlowery** [bdkjones/CodeKit#703]
I am using dart-sass, and i'm on version 3.21 Build 34472. @use and @forward are not working with mixins and variables.

This is my folder structure:
```
styles/
├─ settings/
│  ├─ _colors.scss
│  ├─ _index.scss
│  ├─ _typography.scss
site.scss
```

I have my color variables in `_colors.scss`, like `$coooler: #ffffff`. 
in typography I have mixins like:
```scss
@mixin calm-voice() {
	font-family: sans-serif;
	font-size: 1rem;
	line-height: 1.4;
}
```
then in `_index.scss` I have 
```scss
@forward 'colors';
@forward 'typography';
```

From my understanding, this is the correct way to setup index files in sass.

Then I try and use this mixin and variable in `site.scss` like so:

```scss
@use 'settings' as *;

body {
	color: $coooler;
	@include calm-voice;
}
```

Codekit throws out this error, which makes no sense because the variable _is defined_ - 
```
Dart Sass failed with this error: Undefined variable.
   ╷
49 │     color: $coooler;
   │            ^^^^^^^^
   ╵
  site.scss 49:9  root stylesheet
  ```
  
  Has anyone gotten the @use and @forward rules to work in codekit with index scss files?

**Comment by bdkjones** [comment]
You sure you meant to have three "o"'s in the word "cooler"?

CodeKit just runs Dart Sass. It does not change the way Dart Sass resolves imported files. If you run Dart Sass yourself from the command line, you should get the same result.

**Comment by bdlowery** [comment]
So with vite I'm able to do this:
```scss
@use 'settings' as *;

body {
    color: $coooler;
    @include calm-voice;
}
```

but with codekit I need to do this

```scss
@use 'settings/' as *;

body {
    color: $coooler;
    @include calm-voice;
}
```
(notice the slash at the end of settings/)

Everything i've seen with sass modules, and the @use and @forward rule shows that you don't need to do anything with the filepath other than just stating the folder name, no extra slashes or anything. It works that way in Vite... but not codekit?

Could it be codekits dependency tree doing anything?
